// <auto-generated />
namespace OFXUpload.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetransactionmovementfk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetransactionmovementfk));
        
        string IMigrationMetadata.Id
        {
            get { return "201906260055555_update-transaction-movement-fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
