//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFXUpload.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialAccountMovement
    {
        public int Id { get; set; }
        public Nullable<int> FinancialAccountBalanceId { get; set; }
        public string Description { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Comment { get; set; }
    
        public virtual FinancialAccountBalance FinancialAccountBalance { get; set; }
    }
}
