//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFXUpload.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinancialContextEntities : DbContext
    {
        public FinancialContextEntities()
            : base("name=FinancialContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<FinancialAccount> FinancialAccounts { get; set; }
        public virtual DbSet<FinancialAccountBalance> FinancialAccountBalances { get; set; }
        public virtual DbSet<FinancialAccountMovement> FinancialAccountMovements { get; set; }
        public virtual DbSet<FinancialAccountTransaction> FinancialAccountTransactions { get; set; }
    }
}
