//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFXUpload.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialAccountTransaction
    {
        public int Id { get; set; }
        public int TransactionId { get; set; }
        public int MovementId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string InitiatorTransactionKey { get; set; }
        public string AcquirerTransactionKey { get; set; }
    
        public virtual FinancialAccountMovement FinancialAccountMovement { get; set; }
    }
}
