//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFXUpload.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialAccountBalance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialAccountBalance()
        {
            this.FinancialAccountMovements = new HashSet<FinancialAccountMovement>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> InitialDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int FinancialAccountId { get; set; }
        public Nullable<decimal> InitialBalance { get; set; }
        public Nullable<decimal> EndBalance { get; set; }
    
        public virtual FinancialAccount FinancialAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinancialAccountMovement> FinancialAccountMovements { get; set; }
    }
}
